title: Release & Heal
email: din@email.se
description: >-
  Välkommen till Release & Heal – din plats för healing, vägledning och personlig utveckling.
baseurl: "" # no subpath for custom domain
url: "https://releaseandheal.se" # set to your custom domain
theme: minima
lang: sv


